{{- if and .Values.rbac.create .Values.rbac.cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["finops.devopsideas.com"]
    resources: ["finopsscalepolicies", "finopsscalepolicies/status", "finopsoperatorconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "namespaces", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
