apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}-metrics-auth-role
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
