{{- if and .Values.rbac.create .Values.rbac.cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "finops-scaling-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "finops-scaling-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
