{{- if .Values.webhook.certManager }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.webhook.certs.issuerName }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
