apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "finops-scaling-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "finops-scaling-operator.fullname" . }}-leader-election-role
  apiGroup: rbac.authorization.k8s.io
