{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}-metrics-service
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: {{ .Values.metrics.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "finops-scaling-operator.selectorLabels" . | nindent 4 }}
{{- end }}
