apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finops-scaling-operator.serviceAccountName" . }}
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
  {{- with .Values.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
