{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "finops-scaling-operator.fullname" . }}-webhook-service
  labels:
    {{- include "finops-scaling-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: {{ .Values.webhook.target_port }}
      protocol: TCP
      name: webhook
  selector:
    {{- include "finops-scaling-operator.selectorLabels" . | nindent 4 }}
{{- end }}
