# This rule is not used by the project scaling-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to finops.devopsideas.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: finopsscalepolicy-viewer-role
rules:
- apiGroups:
  - finops.devopsideas.com
  resources:
  - finopsscalepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - finops.devopsideas.com
  resources:
  - finopsscalepolicies/status
  verbs:
  - get
