apiVersion: finops.devopsideas.com/v1alpha1
kind: FinOpsOperatorConfig
metadata:
  labels:
    app.kubernetes.io/name: scaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: global-config
spec:
  excludedNamespaces:
    - "kube-system"
    - "kube-public"
    - "kube-node-lease"
    - "local-path-storage"
    - "scaling-operator-system"
  excludedDeployments:
    - namespace: "istio-system"
      name: "istio-ingressgateway"
  maxParallelOperations: 5
  checkInterval: "5m"  # Operator checks every 5 minutes
  forceScaleDown: false  # Admin-controlled, forces scale-down if no CR is present. Default is false
  forceScaleDownSchedule: # Schedule to follow when forceScaleDown is set to True
     days: ["*"] 
     startTime: "21:00"
     endTime: "06:00"
  forceScaleDownTimezone: America/Toronto # Timezone for global scaledown

