apiVersion: finops.devopsideas.com/v1alpha1
kind: FinOpsScalePolicy
metadata:
  labels:
    app.kubernetes.io/name: scaling-operator
    app.kubernetes.io/managed-by: kustomize
  name: finopsscalepolicy-sample
spec:
  optOut: false  # If true, this namespace is fully excluded from scaling
  defaultSchedule:  ["Mon", "Tue", "Wed", "Thu", "Fri"]  
  timezone: "America/Toronto"  # Default UTC, can be overridden per policy
  deployments:
    - name: "web-app"
      schedule: # Custom scale-down time for this deployment
        days: ["*"] # Override default to scale down every day
        startTime: "22:00"
        endTime: "06:00"
      minReplicas: 0
    - name: "worker-app"
      minReplicas: 1
