//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentScale) DeepCopyInto(out *DeploymentScale) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(ScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentScale.
func (in *DeploymentScale) DeepCopy() *DeploymentScale {
	if in == nil {
		return nil
	}
	out := new(DeploymentScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludedDeploy) DeepCopyInto(out *ExcludedDeploy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludedDeploy.
func (in *ExcludedDeploy) DeepCopy() *ExcludedDeploy {
	if in == nil {
		return nil
	}
	out := new(ExcludedDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsOperatorConfig) DeepCopyInto(out *FinOpsOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsOperatorConfig.
func (in *FinOpsOperatorConfig) DeepCopy() *FinOpsOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(FinOpsOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinOpsOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsOperatorConfigList) DeepCopyInto(out *FinOpsOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FinOpsOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsOperatorConfigList.
func (in *FinOpsOperatorConfigList) DeepCopy() *FinOpsOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(FinOpsOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinOpsOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsOperatorConfigSpec) DeepCopyInto(out *FinOpsOperatorConfigSpec) {
	*out = *in
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedDeployments != nil {
		in, out := &in.ExcludedDeployments, &out.ExcludedDeployments
		*out = make([]ExcludedDeploy, len(*in))
		copy(*out, *in)
	}
	if in.ForceScaleDownSchedule != nil {
		in, out := &in.ForceScaleDownSchedule, &out.ForceScaleDownSchedule
		*out = new(GlobalScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsOperatorConfigSpec.
func (in *FinOpsOperatorConfigSpec) DeepCopy() *FinOpsOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FinOpsOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsOperatorConfigStatus) DeepCopyInto(out *FinOpsOperatorConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsOperatorConfigStatus.
func (in *FinOpsOperatorConfigStatus) DeepCopy() *FinOpsOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(FinOpsOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsScalePolicy) DeepCopyInto(out *FinOpsScalePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsScalePolicy.
func (in *FinOpsScalePolicy) DeepCopy() *FinOpsScalePolicy {
	if in == nil {
		return nil
	}
	out := new(FinOpsScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinOpsScalePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsScalePolicyList) DeepCopyInto(out *FinOpsScalePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FinOpsScalePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsScalePolicyList.
func (in *FinOpsScalePolicyList) DeepCopy() *FinOpsScalePolicyList {
	if in == nil {
		return nil
	}
	out := new(FinOpsScalePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FinOpsScalePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsScalePolicySpec) DeepCopyInto(out *FinOpsScalePolicySpec) {
	*out = *in
	if in.DefaultSchedule != nil {
		in, out := &in.DefaultSchedule, &out.DefaultSchedule
		*out = new(ScheduleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = make([]DeploymentScale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsScalePolicySpec.
func (in *FinOpsScalePolicySpec) DeepCopy() *FinOpsScalePolicySpec {
	if in == nil {
		return nil
	}
	out := new(FinOpsScalePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinOpsScalePolicyStatus) DeepCopyInto(out *FinOpsScalePolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinOpsScalePolicyStatus.
func (in *FinOpsScalePolicyStatus) DeepCopy() *FinOpsScalePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FinOpsScalePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalScheduleSpec) DeepCopyInto(out *GlobalScheduleSpec) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalScheduleSpec.
func (in *GlobalScheduleSpec) DeepCopy() *GlobalScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleSpec) DeepCopyInto(out *ScheduleSpec) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleSpec.
func (in *ScheduleSpec) DeepCopy() *ScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduleSpec)
	in.DeepCopyInto(out)
	return out
}
